; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = master, slave_a, slave_b, slave_c

[env]
platform = espressif8266
board = esp12e
framework = arduino
upload_speed = 921600
monitor_speed = 921600

[env:master]
upload_port = COM10
lib_deps = bodmer/TFT_eSPI @ ^2.5.43
build_flags =
  -DDEVICE_ROLE_MASTER=1
  -DUSER_SETUP_LOADED=1
  -DST7735_DRIVER=1
  -DTFT_WIDTH=128
  -DTFT_HEIGHT=160
  -DTFT_MOSI=13
  -DTFT_SCLK=14
  -DTFT_CS=15
  -DTFT_DC=0
  -DTFT_RST=2
  -DLOAD_GLCD=1
  -DLOAD_FONT2=1
  -DSUPPORT_TRANSACTIONS=1
  -DSPI_FREQUENCY=27000000

[env:slave_a]
upload_port = COM11
build_src_filter = +<*> -<tf_card_test.cpp> -<tf_mode_store.cpp>
lib_deps = adafruit/Adafruit INA219 @ ^1.2.3
build_flags =
  -DDEVICE_ROLE_MASTER=0
  -DDEVICE_SLAVE_INDEX=0

[env:slave_b]
upload_port = COM12
build_src_filter = +<*> -<tf_card_test.cpp> -<tf_mode_store.cpp>
build_flags =
  -DDEVICE_ROLE_MASTER=0
  -DDEVICE_SLAVE_INDEX=1

[env:slave_c]
upload_port = COM13
build_src_filter = +<*> -<tf_card_test.cpp> -<tf_mode_store.cpp>
build_flags =
  -DDEVICE_ROLE_MASTER=0
  -DDEVICE_SLAVE_INDEX=2
